"""add disabled and online status to staff

Revision ID: 0da61f693749
Revises: 16b822df1e40
Create Date: 2026-08-18 22:19:30.704031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da61f693749'
down_revision = '16b822df1e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_online')
        batch_op.drop_column('is_disabled')

    # ### end Alembic commands ###
