"""add released_at to document_requests

Revision ID: 375dc94d470f
Revises: 0da61f693749
Create Date: 2026-08-31 21:30:17.934022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375dc94d470f'
down_revision = '0da61f693749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('released_at')

    # ### end Alembic commands ###
