"""add released_at to document_requests

Revision ID: 5e77445c8cda
Revises: 375dc94d470f
Create Date: 2026-08-31 22:30:22.903892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e77445c8cda'
down_revision = '375dc94d470f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('released_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.drop_column('released_at')

    # ### end Alembic commands ###
