"""fsm statuses and correction fields

Revision ID: 6ea867b8ae5d
Revises: 5e77445c8cda
Create Date: 2026-10-08 23:22:12.054641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ea867b8ae5d'
down_revision = '5e77445c8cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correction_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('correction_note', sa.Text(), nullable=True))

    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.alter_column('staff_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('staff_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('note')
        batch_op.drop_column('student_id')
        batch_op.drop_column('accepted')

    with op.batch_alter_table('document_requests', schema=None) as batch_op:
        batch_op.drop_column('correction_note')
        batch_op.drop_column('correction_from')

    # ### end Alembic commands ###
